config/routes.rb
Rails0::Application.routes.draw do

  match 'flows' => 'flows#index'
  match 'flows/:id' => 'flows#launch', :as => :launch_flow, :via => :post

  match 'work/:username' => 'work#index', :as => :work
  match 'work/:username/:id' => 'work#update', :as => :workitem_update, :via => :post
  match 'work/:username/:id' => 'work#show', :as => :workitem

  # routes to RuoteKit
  match '/_ruote' => RuoteKit::Application
  match '/_ruote/*path' => RuoteKit::Application
end

app/models/document.rb
class Document

  def self.write(name, content)

    File.open(Rails.root.join('public/docs', name + '.txt').to_s, 'wb') do |f|
      f.write(content)
    end
  end

  def self.read(name)

    File.read(Rails.root.join('public/docs', name + '.txt').to_s)
  end

  def self.publish(name)

    content = read(name)

    Prawn::Document.generate(Rails.root.join('public/pdfs', name + '.pdf')) do
      text(name)
      move_down 30
      text(content)
    end
  end
end

app/models/role.rb
class Role

  ROLES = {
    'chris' =>  %w[ author ],
    'ezra' =>   %w[ author reviewer publisher ],
    'john' =>   %w[ reviewer ]
  }

  def self.by_user(uname)

    ROLES[uname]
  end
end

app/models/workflow.rb
class Workflow

  attr_reader :name, :path

  def self.all

    Dir[Rails.root.join('flows/*.rad')].collect { |pa|
      File.basename(pa).split('.').first
    }.collect { |name|
      Workflow.new(name)
    }
  end

  def self.find(name)

     Workflow.new(name)
  end

  def initialize(name)

    @name = name
    @path = Rails.root.join('flows', @name + '.rad').to_s
  end

  def launch(initial_fields={})

    RuoteKit.engine.launch(@path, initial_fields)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController

  def index

    @flows = Workflow.all
  end

  def launch

    wfid = Workflow.find(params[:id]).launch

    flash[:notice] = "launched new flow #{wfid}"

    redirect_to flows_path
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController

  def index

    @workitems = Role.by_user(params[:username]).map { |role|
      RuoteKit.storage_participant.by_participant(role)
    }.reduce(&:+)
  end

  def show

    @workitem = RuoteKit.storage_participant.by_fei(params[:id])

    render_form_if_any
  end

  def update

    @workitem = RuoteKit.storage_participant.by_fei(params[:id])

    if params[:fields]
      @workitem.fields = Rufus::Json.decode(params[:fields])
    else
      params.keys.select { |k|
        k.to_s.match(/^field_/)
      }.each { |f|
        @workitem.fields[f.to_s[6..-1]] = params[f]
      }
    end

    if params[:commit] == 'proceed'

      RuoteKit.storage_participant.proceed(@workitem)

      flash[:notice] = "workitem #{params[:id]} proceeded"

    elsif params[:commit] == 'update'

      RuoteKit.storage_participant.update(@workitem)

      flash[:notice] = "workitem #{params[:id]} updated"
    end

    redirect_to work_path(params[:username])
  end

  protected

  def render_form_if_any

    forms = Rails.root.join('app/views/work/forms/')

    pname = @workitem.participant_name
    task = (@workitem.fields['params']['task'] || 'NONE').strip.gsub(' ', '_')

    [ "#{pname}__#{task}.erb", "#{task}.erb", "#{pname}.erb" ].each do |f|

      path = forms.join(f).to_s

      render :file => path if File.exist?(path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flows/index.erb
<h1>flows</h1>

<ul>
  <% @flows.each do |flow| %>
    <li>
      <%= link_to flow.name, launch_flow_path(flow.name), :method => :post %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lux, Rails and ruote</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="nav">
  <%= link_to 'flows', flows_path %>
  <% %w[ chris ezra john ].each do |r| %>
    <%= link_to "work/#{r}", work_path(r) %>
  <% end %>
</div>

<% if notice = flash[:notice] %>
  <div class="notice"><%= flash.notice %></div>
<% end %>

<%= yield %>
<%= debug(params)%>
</body>
</html>

app/views/work/forms/author.erb
<h1>workitem <%= params[:id].split('!').last %> for <%= params[:username] %> as <%= @workitem.participant_name %></h1>

<%= form_for('update') do |form| %>

  <%= hidden_field_tag('field_stamp', params[:username]) %><br/>

  doc name:<br/>
  <%= text_field_tag('field_doc_name', @workitem.fields['doc_name'] || '') %><br/>

  doc content:<br/>
  <%= text_area_tag('field_doc_content', '', :style => 'width: 420px; height: 210px; font-family: sans-serif; font-size: 14px') %><br/>

  <br/>

  <%= submit_tag 'proceed' %>
  <%= submit_tag 'update' %>
  <%= submit_tag 'cancel' %>
<% end %>

app/views/work/forms/reviewer.erb
<h1>workitem <%= params[:id].split('!').last %> for <%= params[:username] %> as <%= @workitem.participant_name %></h1>

<%= form_for('update') do |form| %>

  <%= hidden_field_tag('field_stamp', params[:username]) %><br/>

  doc name:<br/>
  <pre><%= @workitem.fields['doc_name'] %></pre>

  doc content:<br/>
  <pre><%= Document.read(@workitem.fields['doc_name']) %></pre>

  approved:<br/>
  <%= check_box_tag('field_approved', 'true') %>

  <br/>

  <%= submit_tag 'proceed' %>
  <%= submit_tag 'update' %>
  <%= submit_tag 'cancel' %>
<% end %>

app/views/work/index.erb
<h1>work for user <%= params[:username] %></h1>

<ul>
  <% @workitems.each do |wi| %>
    <li>
      <%= link_to wi.fei.wfid, workitem_path(params[:username], wi.fei.sid) %>
      <%= wi.fields.inspect %>
    </li>
  <% end %>
</ul>

app/views/work/show.erb
<h1>workitem <%= params[:id].split('!').last %> for <%= params[:username] %></h1>

<%= form_for('update') do |form| %>
  <%= text_area_tag('fields', Rufus::Json.pretty_encode(@workitem.fields), :style => 'width: 420px; height: 210px; font-family: sans-serif; font-size: 14px') %>
  <br/>
  <%= submit_tag 'proceed' %>
  <%= submit_tag 'update' %>
  <%= submit_tag 'cancel' %>
<% end %>